version: "3.7"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: "keycloak-db"
    image: postgres:12.2
    volumes:
      - ./data/postgres_volume/:/var/lib/postgresql/data/
      - ./data/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    # restart: "always"
  keycloak:
    container_name: "keycloak-app"
    image: jboss/keycloak:9.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    # restart: "always"
    ports:
      - 9000:8080
    depends_on:
      - postgres
  ang-mat:
    container_name: ang-mat
    image: ang-material:v0.1.0
    ports:
      - 8080:80
    # volumes: 
    #   - ./data/app
  
  

networks:
  keycloak-network:
    name: keycloak-network
