name: wfac

# trigger the workflow when someone pushes the code to repo
on:
  push

jobs:
  docker:
    name: Publish - Github Package
    runs-on: ubuntu-18.04
    env:
      REPO: docker.pkg.github.com/${{ github.repository }}/wfac:v0.0.1
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t $REPO .
      
      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $REPO